-- pgvector
CREATE EXTENSION IF NOT EXISTS vector;


-- -----------------------------------------------------------------------------
-- 1. document
-- -----------------------------------------------------------------------------

CREATE TABLE document (
                          id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          tenant_id                   BIGINT NOT NULL,
                          owner_principal_id          VARCHAR(255) NOT NULL,

                          title                       VARCHAR(255) NOT NULL,
                          latest_upload_version_no    BIGINT NOT NULL DEFAULT 0,
                          latest_embedding_version_no BIGINT NOT NULL DEFAULT 0,
                          searchable_version_id       BIGINT,

                          deleted_at                  TIMESTAMPTZ,
                          purged_at                   TIMESTAMPTZ,
                          created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_document_tenant
                              FOREIGN KEY (tenant_id)
                                  REFERENCES tenant(id),
                          CONSTRAINT uk_document_id_tenant
                              UNIQUE (id, tenant_id),
                          CONSTRAINT ck_document_latest_upload_version_no
                              CHECK (latest_upload_version_no >= 0),
                          CONSTRAINT ck_document_latest_embedding_version_no
                              CHECK (latest_embedding_version_no >= 0),
                          CONSTRAINT ck_document_embedding_not_ahead_of_upload
                              CHECK (latest_embedding_version_no <= latest_upload_version_no),
                          CONSTRAINT ck_document_purged_after_deleted
                              CHECK (purged_at IS NULL OR deleted_at IS NOT NULL)
);

COMMENT ON COLUMN document.latest_upload_version_no IS
    '마지막으로 발급된 version_no. 다음 버전 번호 채번에 쓰는 카운터.';
COMMENT ON COLUMN document.latest_embedding_version_no IS
    '임베딩이 완료된 가장 최신 version_no.';
COMMENT ON COLUMN document.searchable_version_id IS
    '검색 대상 document_version 의 PK. latest_embedding_version_no 이하 버전만 지정한다.';
COMMENT ON COLUMN document.purged_at IS
    '물리 정리 완료 시각. 청크 삭제와 원본 삭제가 모두 끝난 뒤 마지막에 기록한다. '
    'NULL 이면 아직 정리되지 않았다는 뜻이므로 스케줄러가 다시 집는다.';


-- -----------------------------------------------------------------------------
-- 2. document_version
-- -----------------------------------------------------------------------------

CREATE TABLE document_version (
                                  id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  document_id                 BIGINT NOT NULL,
                                  version_no                  BIGINT NOT NULL,
                                  embedding_version_no        BIGINT NOT NULL,

                                  source_object_key           VARCHAR(1024) NOT NULL,
                                  original_filename           BYTEA NOT NULL,
                                  mime_type                   VARCHAR(100) NOT NULL,
                                  file_size                   BIGINT NOT NULL,
                                  content_hash                VARCHAR(128) NOT NULL,

                                  source_metadata             JSONB,
                                  extracted_metadata          JSONB,

                                  chunk_count                 INTEGER,
                                  indexed_at                  TIMESTAMPTZ,

                                  created_by_principal_id     VARCHAR(255) NOT NULL,
                                  created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                  CONSTRAINT fk_document_version_document
                                      FOREIGN KEY (document_id)
                                          REFERENCES document(id),
                                  CONSTRAINT uk_document_version
                                      UNIQUE (document_id, version_no),
                                  CONSTRAINT uk_document_version_id_document
                                      UNIQUE (id, document_id),
                                  CONSTRAINT ck_document_version_no
                                      CHECK (version_no > 0),
                                  CONSTRAINT ck_document_version_embedding_version_no
                                      CHECK (embedding_version_no > 0),
                                  CONSTRAINT ck_document_version_file_size
                                      CHECK (file_size >= 0),
                                  CONSTRAINT ck_document_version_chunk_count
                                      CHECK (chunk_count IS NULL OR chunk_count >= 0)
);

COMMENT ON COLUMN document_version.original_filename IS
    '암호화 대상. opencrypto 함수로 암복호화한다.';
COMMENT ON COLUMN document_version.extracted_metadata IS
    '문서 파싱이 아니라 AI 가 생성한 메타데이터.';


-- document.searchable_version_id 의 복합 FK 는 document_version 생성 후 추가한다.
ALTER TABLE document
    ADD CONSTRAINT fk_document_searchable_version
        FOREIGN KEY (searchable_version_id, id)
            REFERENCES document_version(id, document_id);

-- =========================================================
-- 3. indexing_job
-- =========================================================

CREATE TABLE indexing_job (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_event_id             UUID NOT NULL,
    document_id                 BIGINT NOT NULL,
    document_version_id         BIGINT NOT NULL,
    kafka_topic                 VARCHAR(255) NOT NULL,
    kafka_partition             INTEGER NOT NULL,
    kafka_offset                BIGINT NOT NULL,

    status                      VARCHAR(30) NOT NULL,
    attempt_count               INTEGER NOT NULL DEFAULT 0,
    next_retry_at               TIMESTAMPTZ,

    worker_id                   VARCHAR(255),
    last_error_code             VARCHAR(100),
    last_error_message          TEXT,
    trace_id                    VARCHAR(255),
    phase                       VARCHAR(30),

    started_at                  TIMESTAMPTZ,
    completed_at                TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_indexing_job_source_event
        UNIQUE (source_event_id),
    CONSTRAINT fk_indexing_job_document_version
        FOREIGN KEY (document_version_id, document_id)
        REFERENCES document_version(id, document_id),
    CONSTRAINT ck_indexing_job_status
        CHECK (status IN (
            'PENDING',
            'PROCESSING',
            'RETRY_WAIT',
            'COMPLETED',
            'FAILED'
        )),
    CONSTRAINT ck_indexing_job_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_indexing_job_kafka_topic
        CHECK (BTRIM(kafka_topic) <> ''),
    CONSTRAINT ck_indexing_job_kafka_partition
        CHECK (kafka_partition >= 0),
    CONSTRAINT ck_indexing_job_kafka_offset
        CHECK (kafka_offset >= 0)
);

CREATE UNIQUE INDEX uq_indexing_job_active_version
    ON indexing_job (document_version_id)
    WHERE status IN ('PENDING', 'PROCESSING', 'RETRY_WAIT');

-- source_event_id 에는 의도적으로 FK 를 걸지 않는다.
-- Outbox 행은 발행 후 정리할 수 있어야 하지만 Job 의 이력은 더 오래 남긴다.
-- kafka_topic + kafka_partition + kafka_offset은 수신한 Kafka record의 불변 위치다.


-- =========================================================
-- 4. document_chunk
-- =========================================================

CREATE TABLE document_chunk (
                                id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                tenant_id                   BIGINT NOT NULL,
                                document_version_id         BIGINT NOT NULL,
                                document_id                 BIGINT NOT NULL,
                                chunk_no                    INTEGER NOT NULL,

                                content                     TEXT NOT NULL,
                                content_hash                VARCHAR(128) NOT NULL,
                                token_count                 INTEGER,

                                page_from                   INTEGER,
                                page_to                     INTEGER,
                                section_path                VARCHAR(1024),
                                metadata                    JSONB,

                                embedding                   VECTOR(1536) NOT NULL,
                                embedded_at                 TIMESTAMPTZ NOT NULL,

                                created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                CONSTRAINT uk_document_chunk
                                    UNIQUE (document_version_id, chunk_no),
                                CONSTRAINT fk_document_chunk_version_document
                                    FOREIGN KEY (document_version_id, document_id)
                                        REFERENCES document_version(id, document_id),
                                CONSTRAINT fk_document_chunk_document_tenant
                                    FOREIGN KEY (document_id, tenant_id)
                                        REFERENCES document(id, tenant_id),
                                CONSTRAINT ck_document_chunk_no
                                    CHECK (chunk_no >= 0),
                                CONSTRAINT ck_document_chunk_token_count
                                    CHECK (token_count IS NULL OR token_count >= 0),
                                CONSTRAINT ck_document_chunk_page_range
                                    CHECK (
                                        page_from IS NULL
                                            OR page_to IS NULL
                                            OR page_from <= page_to
                                        )
);
